# Generated by Django 3.2.6 on 2021-08-14 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='respuesta',
            name='correcta',
            field=models.BooleanField(default=False),
        ),
    ]
