# Generated by Django 3.2.6 on 2021-08-11 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('puntaje', models.IntegerField()),
                ('fecha_ult_acceso', models.DateField(auto_now_add=True)),
                ('estado', models.IntegerField()),
            ],
        ),
    ]
